name = "GZip"
uuid = "92fee26a-97fe-5a0c-ad85-20a5f3185b63"
authors = ["staticfloat@gmail.com <staticfloat@gmail.com>"]
version = "0.5.2"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
