name = "GZip"
uuid = "92fee26a-97fe-5a0c-ad85-20a5f3185b63"
authors = ["staticfloat@gmail.com <staticfloat@gmail.com>", "Viral B. Shah <viral@mayin.org>"]
version = "0.8.0"

[deps]
Zlib_jll = "83775a58-1f1d-513f-b197-d71354ab007a"
ZlibNG_jll = "c62bbaca-5768-5b75-85e2-9a0ea54e1624"

[compat]
Zlib_jll = "1.2"
ZlibNG_jll = "2"
Aqua = "0.8"
Test = "1.0"
julia = "1.9"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
