[general]
library_name = "ZlibNG_jll.libzng_path"
output_file_path = "../src/zlibng_h.jl"
module_name = "ZlibNG_h"
jll_pkg_name = "ZlibNG_jll"
export_symbol_prefixes = ["Z_", "ZNG_"]
use_julia_native_enum_type = true
print_using_CEnum = false

[codegen]
is_function_strictly_typed = true
opaque_func_arg_as_PtrCvoid = true
opaque_as_mutable_struct = true
